
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author damA
 */
public class AñadirPelicula extends javax.swing.JDialog {
Conectar conectar = null;

    /**
     * Creates new form AñadirPelicula
     */
    public AñadirPelicula(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Cargamos el comboBox
        consultar_director(jComboBoxDirector);
        consultar_sala(jComboBoxSala);
        consultar_tematica(jComboBoxTematica);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxDirector = new javax.swing.JComboBox<>();
        jComboBoxTematica = new javax.swing.JComboBox<>();
        jComboBoxSala = new javax.swing.JComboBox<>();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldFecha = new javax.swing.JTextField();
        jTextFieldAñoEstreno = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jButtonInsert = new javax.swing.JButton();
        jButtonNewDirector = new javax.swing.JButton();
        jButtonNewTematica = new javax.swing.JButton();
        jButtonNewSala = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Titulo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Director");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Fecha proyeccion");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Año estreno");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tematica");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Precio entrada");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Sala");

        jComboBoxDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDirectorActionPerformed(evt);
            }
        });

        jComboBoxTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTematicaActionPerformed(evt);
            }
        });

        jButtonInsert.setBackground(new java.awt.Color(255, 204, 255));
        jButtonInsert.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonInsert.setText("Insertar");
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });

        jButtonNewDirector.setBackground(new java.awt.Color(255, 204, 255));
        jButtonNewDirector.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButtonNewDirector.setText("Nuevo director");
        jButtonNewDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewDirectorActionPerformed(evt);
            }
        });

        jButtonNewTematica.setBackground(new java.awt.Color(255, 204, 255));
        jButtonNewTematica.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButtonNewTematica.setText("Nueva tematica");
        jButtonNewTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewTematicaActionPerformed(evt);
            }
        });

        jButtonNewSala.setBackground(new java.awt.Color(255, 204, 255));
        jButtonNewSala.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButtonNewSala.setText("Nueva sala");
        jButtonNewSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewSalaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 255));
        jLabel8.setText("AÑADIR PELICULA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(32, 32, 32)
                                .addComponent(jTextFieldFecha))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(57, 57, 57)
                                .addComponent(jTextFieldAñoEstreno))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxTematica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxDirector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxSala, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldTitulo)
                                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonNewDirector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonNewTematica, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jButtonNewSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewDirector))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldAñoEstreno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxTematica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewTematica))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewSala))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonInsert)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDirectorActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jComboBoxDirectorActionPerformed

    private void jComboBoxTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTematicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTematicaActionPerformed

    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed
        // TODO add your handling code here:
        String titulo = jTextFieldTitulo.getText();
        var director = jComboBoxDirector.getSelectedItem();
        String fechaProyec = jTextFieldFecha.getText();
        String añoEstreño = jTextFieldAñoEstreno.getText();
        var tematica = jComboBoxTematica.getSelectedItem();
        String precioEntrada = jTextFieldPrecio.getText();
        var sala = jComboBoxSala.getSelectedItem();
        
        String[] idDirector= director.toString().split("-");
        String Did=idDirector[0];
        
        String[] idTematica= tematica.toString().split("-");
        String Teid=idTematica[0];
        
        String[] idSala= sala.toString().split("-");
        String Said=idSala[0];
        
        
        

        
        PreparedStatement ps=null;
        conectar = new Conectar();
        Connection conexion = conectar.getConexion();
        
        String sql= "insert into pelicula(titulo,director,fechaProyeccion,añoEstreno,tematica,precioEntrada,sala) "
                + "values ('"+titulo+"','"+Did+"','"+fechaProyec+"','"+añoEstreño+"','"+Teid+"','"+precioEntrada+"','"+Said+"')";
        
        try {
          ps = conexion.prepareStatement(sql);
          ps.executeUpdate();
            
        } catch (SQLException ex) {
            Logger.getLogger(AñadirDirector.class.getName()).log(Level.SEVERE, null, ex);
        }

        dispose();
    }//GEN-LAST:event_jButtonInsertActionPerformed

 
    private void jButtonNewDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewDirectorActionPerformed
        // TODO add your handling code here:
        AñadirDirector intrDatos = new AñadirDirector(null, true);
        intrDatos.setVisible(true);
        consultar_director(jComboBoxDirector);
        
    }//GEN-LAST:event_jButtonNewDirectorActionPerformed

    private void jButtonNewTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewTematicaActionPerformed
        // TODO add your handling code here:
        AñadirTematica intrDatos = new AñadirTematica(null, true);
        intrDatos.setVisible(true);
        consultar_tematica(jComboBoxTematica);
    }//GEN-LAST:event_jButtonNewTematicaActionPerformed

    private void jButtonNewSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewSalaActionPerformed
        // TODO add your handling code here:
        AñadirSala intrDatos = new AñadirSala(null, true);
        intrDatos.setVisible(true);
        consultar_sala(jComboBoxSala);
    }//GEN-LAST:event_jButtonNewSalaActionPerformed

    public void consultar_director(JComboBox cbox_director){
        PreparedStatement ps=null;
        conectar = new Conectar();
        Connection conexion = conectar.getConexion();
        String sql = "SELECT idDirector,nombre FROM director";
        try {
            ps = conexion.prepareStatement(sql);
            ResultSet result = ps.executeQuery();
            

            
            while (result.next()) {
                cbox_director.addItem(result.getString("idDirector")+"-" + result.getString("nombre"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void consultar_sala(JComboBox cbox_sala){
        PreparedStatement ps=null;
        conectar = new Conectar();
        Connection conexion = conectar.getConexion();
        String sql = "SELECT idSala,nombre FROM sala";
        try {
            ps = conexion.prepareStatement(sql);
            ResultSet result = ps.executeQuery();
            

            
            while (result.next()) {
                cbox_sala.addItem(result.getString("idSala")+"-" + result.getString("nombre"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
        
    public void consultar_tematica(JComboBox cbox_tematica){
        PreparedStatement ps=null;
        conectar = new Conectar();
        Connection conexion = conectar.getConexion();
        String sql = "SELECT idTematica,nombre FROM tematica";
        try {
            ps = conexion.prepareStatement(sql);
            ResultSet result = ps.executeQuery();

            
            while (result.next()) {
                cbox_tematica.addItem(result.getString("idTematica")+"-" + result.getString("nombre"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
  
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jButtonNewDirector;
    private javax.swing.JButton jButtonNewSala;
    private javax.swing.JButton jButtonNewTematica;
    private javax.swing.JComboBox<String> jComboBoxDirector;
    private javax.swing.JComboBox<String> jComboBoxSala;
    private javax.swing.JComboBox<String> jComboBoxTematica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextFieldAñoEstreno;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
