/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Incidencias;

import Profesores.InsertarProfesor;
import Profesores.ProfesoresPrincipal;
import baseDatos.Conectar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author damA
 */
public class MostrarIncidencias extends javax.swing.JDialog {

    Conectar conectar = null;

    /**
     * Creates new form MostrarIncidencias
     */
    public MostrarIncidencias(javax.swing.JDialog parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        
        rellenoTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableIncidencias = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableIncidencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableIncidencias.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableIncidencias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTableIncidencias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1109, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   public void rellenoTabla() throws SQLException {
        DefaultTableModel dtm = new DefaultTableModel();
        //Creamos las columnas que tendra la tabla
        dtm.setColumnIdentifiers(new String[]{"Creada por", "Descripcion", "Descripcion tecnica", "Horas de reparacion", "Estado", "Lazmiento", "Inicio reparacion", "Fin reparacion", "Nivel", "Clase", "Edificio", "Observaciones"});
        //Elemento para ordenar la tabla
        TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<TableModel>(dtm);
        //Ordenamos la tabla segun las columnas
        jTableIncidencias.setRowSorter(elQueOrdena);
        


        //Añadimos las columnas a la tabla
        jTableIncidencias.setModel(dtm);

        conectar = new Conectar();
        Connection conexion = conectar.getConexion();
        String[] incidencia = new String[12];
        if (conexion != null) {

            try {
                Statement s = conexion.createStatement();
                ResultSet rs = s.executeQuery("select p.nombre_completo,inc.descripcion,inc.desc_tecnica,inc.horas, \n"
                        + "est.estado,inc.fecha,inc.fecha_ini_rep,inc.fecha_fin_rep,ur.urgencia,\n"
                        + "ub.ubicacion,ed.edificio,inc.observaciones\n"
                        + "from man_incidencias inc\n"
                        + "inner join fp_profesor p on p.id_profesor=inc.id_profesor_crea\n"
                        + "inner join man_estado est on est.id_estado = inc.id_estado\n"
                        + "inner join man_urgencia ur on ur.id_urgencia=inc.nivel_urgencia\n"
                        + "inner join man_ubicacion ub on ub.id_ubicacion=inc.id_ubicacion\n"
                        + "inner join man_edificio ed on ed.id_edificio=ub.id_edificio;");

                while (rs.next()) {
                    //dtm.addRow(rs);
                    incidencia[0] = rs.getString(1);
                    incidencia[1] = rs.getString(2);
                    incidencia[2] = rs.getString(3);
                    incidencia[3] = rs.getString(4);
                    incidencia[4] = rs.getString(5);
                    incidencia[5] = rs.getString(6);
                    incidencia[6] = rs.getString(7);
                    incidencia[7] = rs.getString(8);
                    incidencia[8] = rs.getString(9);
                    incidencia[9] = rs.getString(10);
                    incidencia[10] = rs.getString(11);
                    incidencia[11] = rs.getString(12);

                    

                    dtm.addRow(incidencia);
                }
            } catch (SQLException sQLException) {
                JOptionPane.showMessageDialog(this, "Datos no cargados");
            }
            conexion.close();

        } else {
            JOptionPane.showMessageDialog(this, "Conoxion fallida");
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableIncidencias;
    // End of variables declaration//GEN-END:variables
}
